import "react-toastify/dist/ReactToastify.css";
import MiniDrawer from "@/component/drawer/drawer";
import { Container } from "@mui/material";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session?.user) {
    redirect("/");
  }
  return (
    <html lang="en">
      <body>
        <Container >
          <MiniDrawer>
            {children}
            </MiniDrawer>
        </Container>
      </body>
    </html>
  );
}


